name: Build and Deploy Uberjar

# On pushes to master
on:
  push:
    branches:
      - master

  # Let me run from actions
  workflow_dispatch:

jobs:
  build-uber-jar:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@v2.3.4

      - name: Install-Java-Runtime
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install-Lein
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          lein: latest

      - name: Build-Uberjar
        run: lein uberjar
        shell: bash
  
      - name: Updating website.
        uses: appleboy/ssh-action@master
        with:
          host: howtoplay.wiki 
          username: root
          key: ${{ secrets.ssh }}
          port: ${{ secrets.port }}
          script: |
            "ls"

      - name: Publish-to-website
        uses: nogsantos/scp-deploy@master
        with:
          src: ./target/uberjar/how-to-play-wiki-0.1.0-SNAPSHOT-standalone.jar
          host: howtoplay.wiki 
          remote: ~/ 
          port: ${{ secrets.SSH_PORT }}
          user: root 
          key: ${{ secrets.SSH_KEY }}


