name: update site static generator

# On pushes to master
on:
  push:
    branches:
      - master

  # Let me run from actions
  workflow_dispatch:

jobs:
  build-uber-jar:
    runs-on: ubuntu-latest

    steps:
    - name: Updating website.
      uses: appleboy/ssh-action@master
      with:
        host: howtoplay.wiki
        username: root
        key: ${{ secrets.ssh }}
        passphrase: ${{ secrets.ssh_pass }}
        port: ${{ secrets.port }}
        script: |
          #Pull the wiki contents
          cd how-to-play-wiki-generator
          git stash
          git pull --force origin master
